FROM python:3

WORKDIR /app

COPY requirements.txt requirements.txt

# Install dependencies from requirements.txt
RUN pip install -r requirements.txt

COPY . . 

EXPOSE 8501

CMD ["streamlit", "run", "src/main_frontend.py"]