services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
      target: streamlit
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    volumes:
      - ./data:/app/data 

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: fastapi
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
