FROM python:3

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt requirements.txt

# Install dependencies from requirements.txt
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port that FastAPI will run on
EXPOSE 8000

# Command to run the FastAPI application
#CMD ["uvicorn", "src/api:app", "--reload"]
CMD ["fastapi", "run", "src/api.py", "--port", "8000"]
